In [1]:
#-----------------------NUMPY--------------------------------------

In [2]:
import numpy as np

In [3]:
a = [1,2,3,4,5,6,7,8,9]

In [4]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
b= np.arange(1,10,1) #--- arrange function in numpy use to create an array with evenly spaced values. range (start,stop,step)

In [6]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
c= np.arange(10,100,10)
c

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [8]:
d =np.arange(10,1000,100)
d

array([ 10, 110, 210, 310, 410, 510, 610, 710, 810, 910])

In [9]:
e=np.arange("a","z") #------ Only numbers allowed not string

TypeError: arange() not supported for inputs with DType <class 'numpy.dtypes.StrDType'>.

In [40]:
f = np.arange(0.1,1,0.1) # -----------Decimals/floot allowed.
f

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [ ]:
#-----------------np.zeros-----------------

In [42]:
g = np.zeros(5)  #create an array filled with zeros 
g

array([0., 0., 0., 0., 0.])

In [44]:
h = np.zeros((2,2))  # creates a 2x3 (2 row , 2column )integer array filled with zeros
h

array([[0., 0.],
       [0., 0.]])

In [46]:
i =np.zeros((2,3,5))  # creates a 3D array (2 blocks, 3 rows, 5 columns)
i

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
#------------------------Random and Randint--------------------------

In [48]:
np.random.random() # This function generates random floats between 0 and 1 in an array of a specified shape.

0.6529252497386308

In [50]:
np.random.random(5)

array([0.09151734, 0.18787134, 0.83996866, 0.09729959, 0.67778873])

In [52]:
np.random.random(10)

array([0.14016325, 0.04667192, 0.3442368 , 0.4528365 , 0.48174157,
       0.15900586, 0.81193545, 0.6395972 , 0.74665583, 0.10733154])

In [54]:
np.random.random((2,10)) # 2 row,10 column random floats

array([[0.41714759, 0.82586584, 0.49266681, 0.07210102, 0.18365277,
        0.72593976, 0.99637852, 0.34256545, 0.74537285, 0.93734367],
       [0.77203686, 0.2402416 , 0.28613026, 0.12565833, 0.46951622,
        0.62443977, 0.2243632 , 0.00221581, 0.92342851, 0.64192464]])

In [56]:
np.random.random((5,5))

array([[0.41322753, 0.24337154, 0.41335077, 0.38108142, 0.74719948],
       [0.88095987, 0.40203196, 0.95975822, 0.49501734, 0.29782729],
       [0.58418739, 0.21312212, 0.13550652, 0.75532514, 0.76797209],
       [0.78653312, 0.75588941, 0.09343008, 0.14088707, 0.63050374],
       [0.41765661, 0.38998577, 0.27212499, 0.13512109, 0.68476219]])

In [58]:
np.random.randint(1,10) #This function generates random integers between a given low (inclusive) and high (exclusive) range.

1

In [60]:
np.random.randint(1,100) # generate random number between 1 to 100

10

In [62]:
np.random.randint(1,100,5) # generate 5  random number between 1 to 100

array([57, 26, 72, 76, 82])

In [64]:
np.random.randint(1,10,10)

array([4, 1, 4, 9, 1, 6, 5, 2, 8, 3])

In [ ]:
#   Generating a 2D array of random integers:

In [66]:
np.random.randint(1,100,size=(10,5))

array([[55, 25, 79, 90, 34],
       [34, 33, 72, 82, 87],
       [93,  7, 10, 18, 40],
       [39, 47,  3, 43, 32],
       [74, 30, 63, 79,  6],
       [66, 25, 87, 41,  6],
       [29, 60, 41, 53, 28],
       [69, 87, 68, 68, 21],
       [61, 25, 73, 50, 13],
       [62, 49, 41, 90, 85]])

In [68]:
s =print(np.random.rand(3))

[0.29238642 0.97902752 0.51544903]


In [70]:
np.random.seed(s)
s

In [72]:
np.random.seed(42)

In [ ]:
#---------------------------  Operatores in Numpy -----------------------------

In [74]:
#   1. Arithmetic Operators
#      Addition (+)

k = np.array([1,2,3])
l = np.array([4,5,6])
m =k + l
m

array([5, 7, 9])

In [76]:
#      Subtraction (-)
m =k - l
m

array([-3, -3, -3])

In [78]:
#      Multiplication (*)
m =k * l
m

array([ 4, 10, 18])

In [80]:
#      Division (/)
m =k / l
m

array([0.25, 0.4 , 0.5 ])

In [82]:
#     Exponentiation (**)
m =k ** l
m

array([  1,  32, 729])

In [84]:
#     Floor Division (//)
m =k // l
m

array([0, 0, 0])

In [10]:
import numpy as np


In [ ]:
#-----------------  Comparison Operatores -----------------

In [88]:
#   Greater Than (>)

a = 4>6 
a

False

In [90]:
#   Less Than (<)
a = 4<6 
a

True

In [92]:
#   Greater Than or Equal (>=)
a = 4>=4 
a

True

In [94]:
#    Less Than or Equal (<=)
a = 4<=4 
a

True

In [96]:
#   Equal (==)
a = 4==4 
a

True

In [ ]:
#   Not Equal (!=)

In [98]:
a = 4!=4 
a

False

In [100]:
#  --3. Logical Operators   
#   AND (&)
a = np.array([1,2,3])
b = np.array([4,5,6])
c =  np.array([7,8,9])
a & c

array([1, 0, 1])

In [102]:
#   OR (|)
a = np.array([1,2,3])
b = np.array([4,5,6])
c =  np.array([7,8,9])
a | c

array([ 7, 10, 11])

In [104]:
#   NOT (~)
a = np.array([1,2,3])
b = np.array([4,5,6])
c =  np.array([7,8,9])
e = a =~ c

In [ ]:
# Note = in np you get only mean not mode and medean


In [12]:
# min 
a= np.array([np.arange(0,100)])
np.min(a)

0

In [108]:
np.max(a)

99

In [112]:
np.average(a)

49.5

In [16]:
a.reshape(10,10) 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [68]:
a[5]

IndexError: index 5 is out of bounds for axis 0 with size 1

In [ ]:
#----------------------

In [48]:
r = 5
c = 7
a[r,c]

IndexError: index 5 is out of bounds for axis 0 with size 1